let productos = [
    {id: 1, nombre:"CACAO", cat:"desayuno" , descripcion:"cacao nesquik " , precio: 185, Img:"../multimedia/nesquik.webp"},
    {id: 2, nombre:"CAFE", cat:"desayuno" , descripcion:"Nescafe Dolca" , precio: 245, Img:"../multimedia/cafe1.jpg"},
    {id: 3, nombre:"YERBA", cat:"desayuno" , descripcion:"yerba Cbsé" , precio: 345, Img:"../multimedia/yerba1.jpg"},
    {id: 4, nombre:"YERBA", cat:"desayuno" , descripcion:"yerba La Merced" , precio:420, Img:"../multimedia/Yerba-Mate-La-Merced.webp"},
    {id: 5, nombre:"LECHE", cat:"desayuno" , descripcion:"leche La Serenisima" , precio: 380, Img:"../multimedia/leche la serenisima.webp"},
    {id: 6, nombre:"CHOCOLATE KINDER", cat:"almacen" , descripcion:"tableta de chocolate Kinder " , precio: 235, Img:"../multimedia/Chocolate-Kinder.webp"},
    {id: 7, nombre:"CERVEZA", cat:"bebidas" , descripcion:"cerveza Heineken" , precio: 180, Img:"../multimedia/cerveza1.jpg"},
    {id: 8, nombre:"SHAMPOO", cat:"higiene personal" , descripcion:"Shampoo Pantene" , precio: 335, Img:"../multimedia/shampoo pantene.webp"},
    {id: 9, nombre:"SHAMPOO", cat:"higiene personal" , descripcion:"Shampoo Elvive" , precio: 320, Img:"../multimedia/shampoo elvive.webp"},
    {id: 10, nombre:"ACONDICIONADOR", cat:"higiene personal" , descripcion:"acondicionador Pantene" , precio: 335, Img:"../multimedia/acondicionador pantene.webp"},
    {id: 11, nombre:"ACONDICIONADOR", cat:"higiene personal" , descripcion:"acondicionador Elvive" , precio: 320, Img:"../multimedia/acondicionador elvive.webp"},
    {id: 12, nombre:"JABON", cat:"higiene personal" , descripcion:"jabon de tocador Dove" , precio: 170, Img:"../multimedia/jabon de tocador.webp"},
    {id: 13, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 14, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 15, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 16, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 17, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 18, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 19, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 20, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 21, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 22, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 23, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 24, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 25, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 26, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 27, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 28, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 29, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},
    {id: 30, nombre:"", cat:"" , descripcion:"" , precio: 1, Img:""},

]