let productos = [
    {id: 1, nombre:"CACAO", cat:"desayuno" , descripcion:"cacao nesquik " , precio: 185, Img:"../multimedia/nesquik.webp",cantidad:1 },
    {id: 2, nombre:"CAFE", cat:"desayuno" , descripcion:"Nescafe Dolca" , precio: 245, Img:"../multimedia/cafe1.jpg", cantidad:1},
    {id: 3, nombre:"YERBA", cat:"desayuno" , descripcion:"yerba Cbsé" , precio: 345, Img:"../multimedia/yerba1.jpg", cantidad:1},
    {id: 4, nombre:"YERBA", cat:"desayuno" , descripcion:"yerba La Merced" , precio:420, Img:"../multimedia/Yerba-Mate-La-Merced.webp", cantidad:1},
    {id: 5, nombre:"FIDEOS", cat:"almacen" , descripcion:"fideos 3 vegetales" , precio: 120, Img:"../multimedia/fideos 3 vegetales.webp", cantidad:1},
    {id: 6, nombre:"FIDEOS TIRABUZON", cat:"almacen" , descripcion:"fideos tirabuzon Luchetti" , precio: 82, Img:"../multimedia/fideos tirabuzon.webp", cantidad:1},
    {id: 7, nombre:"AZUCAR", cat:"almacen" , descripcion:"azucar Ledesma" , precio: 115, Img:"../multimedia/azucar Ledesma.webp", cantidad:1},
    {id: 8, nombre:"MAYONESA", cat:"almacen" , descripcion:"mayonesa Hellmann's" , precio: 235, Img:"../multimedia/mayonesa Hellmans.webp", cantidad:1},
    {id: 9, nombre:"PURE DE TOMATES", cat:"almacen" , descripcion:"puré de tomates Arcor" , precio: 85, Img:"../multimedia/pure de tomates.webp", cantidad:1},
    {id: 10, nombre:"CHOCOLATE KINDER", cat:"almacen" , descripcion:"tableta de chocolate Kinder " , precio: 235, Img:"../multimedia/Chocolate-Kinder.webp", cantidad:1},
    {id: 11, nombre:"DULCE DE LECHE", cat:"almacen" , descripcion:"dulce de leche La Serenisima" , precio: 190, Img:"../multimedia/dulce de leche.webp", cantidad:1},
    {id: 12, nombre:"PAPAS FRITAS", cat:"almacen" , descripcion:"papas fritas Lay's" , precio: 280, Img:"../multimedia/papas fritas Lays.webp", cantidad:1},
    {id: 13, nombre:"HARINA INTEGRAL", cat:"almacen" , descripcion:"harina integral Pureza" , precio: 140, Img:"../multimedia/harina integral Pureza.webp", cantidad:1},
    {id: 14, nombre:"LECHE", cat:"desayuno" , descripcion:"leche La Serenisima" , precio: 380, Img:"../multimedia/leche la serenisima.webp", cantidad:1},
    {id: 15, nombre:"MANTECA", cat:"almacen" , descripcion:"manteca Tonadita" , precio: 230, Img:"../multimedia/manteca Tonadita.webp", cantidad:1},
    {id: 16, nombre:"QUESO RALLADO", cat:"almacen" , descripcion:"queso rallado La Paulina" , precio: 230, Img:"../multimedia/queso rallado La Paulina.webp", cantidad:1},
    {id: 17, nombre:"COCA COLA", cat:"bebidas" , descripcion:"gaseosa Coca Cola" , precio: 280, Img:"../multimedia/coca-cola.webp", cantidad:1},
    {id: 18, nombre:"CERVEZA", cat:"bebidas" , descripcion:"cerveza Heineken" , precio: 180, Img:"../multimedia/cerveza1.jpg", cantidad:1},
    {id: 19, nombre:"VINO TINTO", cat:"bebidas" , descripcion:"vino tinto Balbo " , precio: 225, Img:"../multimedia/vino tinto Balbo.webp", cantidad:1},
    {id: 20, nombre:"SHAMPOO", cat:"higiene personal" , descripcion:"Shampoo Pantene" , precio: 335, Img:"../multimedia/shampoo pantene.webp", cantidad:1},
    {id: 21, nombre:"SHAMPOO", cat:"higiene personal" , descripcion:"Shampoo Elvive" , precio: 320, Img:"../multimedia/shampoo elvive.webp", cantidad:1},
    {id: 22, nombre:"ACONDICIONADOR", cat:"higiene personal" , descripcion:"acondicionador Pantene" , precio: 335, Img:"../multimedia/acondicionador pantene.webp", cantidad:1},
    {id: 23, nombre:"ACONDICIONADOR", cat:"higiene personal" , descripcion:"acondicionador Elvive" , precio: 320, Img:"../multimedia/acondicionador elvive.webp", cantidad:1},
    {id: 24, nombre:"JABON", cat:"higiene personal" , descripcion:"jabon de tocador Dove" , precio: 170, Img:"../multimedia/jabon de tocador.webp", cantidad:1},
    {id: 25, nombre:"DESODORANTE", cat:"higiene personal" , descripcion:"Desodorante rexona clinical" , precio: 345, Img:"../multimedia/desodorante clinical.webp", cantidad:1},
    {id: 26, nombre:"ATÚN", cat:"almacen" , descripcion:"atún La Campagnola" , precio: 230, Img:"../multimedia/atun La campagnola.webp", cantidad:1},
    {id: 27, nombre:"PAÑALES", cat:"higiene personal" , descripcion:"pañales Pampers" , precio: 460, Img:"../multimedia/pañales Pampers.webp", cantidad:1},
    {id: 28, nombre:"PAÑALES", cat:"higiene personal" , descripcion:"pañales Huggies" , precio: 380, Img:"../multimedia/pañales Huggies.webp", cantidad:1},
    {id: 29, nombre:"HAMBURGUESAS", cat:"almacen" , descripcion:"hamburguesas Paty" , precio: 510, Img:"../multimedia/hamburguesas Paty.webp", cantidad:1},
    {id: 30, nombre:"JABON LIQUIDO", cat:"limpieza" , descripcion:"jabon liquido Ala" , precio: 360, Img:"../multimedia/jabon liquido Ala.webp", cantidad:1},

]